fun main() {
  println("Set Inmutable - Unidades en Estación")
    val registros = setOf(101, 102, 103, 104, 108, 104, 101, 103)
    println("Códigos de unidades únicas: ${registros}")
  
  println("Operaciones de conjuntos - Control de Rutas")
    val unidadesRutaA = setOf(2, 4, 6, 8, 10)
    val unidadesRutaB = setOf(3, 6, 9, 12)
    println("Unidades Ruta A: ${unidadesRutaA}")
    println("Unidades Ruta B: ${unidadesRutaB}")
    println("Total de unidades operativas (unión): ${unidadesRutaA union unidadesRutaB}")
    println("Unidades compartiendo tramo (intersección): ${unidadesRutaA intersect unidadesRutaB}")
    println("Unidades exclusivas Ruta A (sustracción): ${unidadesRutaA subtract unidadesRutaB}")
    println("Unidades Ruta A: ${unidadesRutaA}")
    println("Unidades Ruta B: ${unidadesRutaB}")
    
    println("Set mutable - Terminales Activas")
    val terminales = mutableSetOf("Quitumbe", "Carcelén", "Ofelia")
    println(terminales)
    terminales.add("Quitumbe")
     println(terminales)
    terminales.add("Playón")
     println(terminales)
    terminales.remove("Carcelén")
     println(terminales)
    println("Verificar si terminal existe: ${"Quitumbe" in terminales}")
    println("Verificar si terminal existe: ${"Carcelén" in terminales}")
}